import type {Moment} from "moment";
import {types} from "sass";
import Null = types.Null;

export default interface TournamentConfigs {
    '24sec_required': Boolean | null,
    cm_time_set_until: Date | String | null,
    tl_edit_enabled: Boolean | null,
    allow_adjusted_score_sheet: Boolean | null,
    allow_mentor_prospect: Number | null,
    coach_license_type_id: Number | null,
    cooldown_minutes: Number | null,
    court_requirement_id: Number | null,
    created_at: Date | String | null,
    default_score_sheet_type: Number | null,
    deleted: Boolean | null,
    earliest_start: String | null,
    expected_duration_minutes: Number | null,
    free_reschedule_until_date: Date | String | null,
    game_dead_line: Date | String | null,
    games_hidden: Boolean | null,
    id: Number | null,
    in_active: Boolean | null,
    information: String | null,
    latest_start: String | null,
    minimum_warmup_minutes: Number | null,
    name: String | null,
    pool_id: Number | null,
    ref_prio: Number | null,
    refs_from_associations: Number | null,
    refs_per_game: Number | null,
    region_id: Number | null,
    registration_dead_line: Date | Moment | String | Null | null,
    report_required: Number | null,
    row_id: Number | null,
    season_sport_id: Number | null,
    short_name: String | null,
    star_rating: Number | null,
    stats_required: Boolean | null,
    tournament_group_id: Number | null,
    transportation_fee: Number | null,
    updated_at: Date | String | null,
}
