import type {Moment} from "moment";
import {types} from "sass";
import Null = types.Null;

export default interface TournamentConfigs {
    '24secRequired': Boolean | null,
    CMTimeSetUntil: Date | String | null,
    TLEditEnabled: Boolean | null,
    allowAdjustedScoreSheet: Boolean | null,
    allowMentorProspect: Number | null,
    coachLicenseTypeId: Number | null,
    cooldownMinutes: Number | null,
    courtRequirementId: Number | null,
    createdAt: Date | String | null,
    defaultScoreSheetType: Number | null,
    deleted: Boolean | null,
    earliestStart: String | null,
    expectedDurationMinutes: Number | null,
    freeRescheduleUntilDate: Date | String | null,
    gameDeadLine: Date | String | null,
    gamesHidden: Boolean | null,
    id: Number | null,
    inActive: Boolean | null,
    information: String | null,
    latestStart: String | null,
    minimumWarmupMinutes: Number | null,
    name: String | null,
    poolId: Number | null,
    refPrio: Number | null,
    refsFromAssociations: Number | null,
    refsPerGame: Number | null,
    regionId: Number | null,
    registrationDeadLine: Date | Moment | String | Null | null,
    reportRequired: Number | null,
    rowId: Number | null,
    seasonSportId: Number | null,
    shortName: String | null,
    starRating: Number | null,
    statsRequired: Boolean | null,
    tournamentGroupId: Number | null,
    transportationFee: Number | null,
    updatedAt: Date | String | null,
}
