// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  plugins: ["~/plugins/loading.client.ts"],
  ssr: false,
  devtools: { enabled: true },
  modules: [
    "@pinia/nuxt",
    "@nuxtjs/tailwindcss",
    "@pinia-plugin-persistedstate/nuxt",
    "@vesp/nuxt-fontawesome",
    "nuxt-vue3-google-signin",
    "@nuxtjs/i18n",
  ],
  i18n: {
    vueI18n: "./i18n.config.ts",
  },
  googleSignIn: {
    clientId: process.env.GOOGLE_CLIENT_ID,
  },
  fontawesome: {
    icons: {
      solid: [
        "bars",
        "chevron-right",
        "chevron-left",
        "calendar",
        "calendar-days",
        "gauge-high",
        "gear",
        "gavel",
        "users-rectangle",
        "stop",
        "filter",
        "list-check",
        "money-bill",
        "pen-to-square",
        "exclamation",
        "exclamation",
        "minus-circle",
        "clock",
        "landmark",
        "users",
        "spinner",
        "check",
        "user",
        "calculator",
        "circle-notch",
        "xmark",
        "arrow-right-from-bracket",
        "eye-slash",
        "eye",
        "exclamation",
        "question",
        "truck-moving",
        "envelope",
        "arrow-right",
        "arrow-left",
        "arrows-up-down",
        "pen",
        "trash-can",
        "sort",
        "angle-up",
        "angle-down",
        "magnifying-glass",
        "upload",
        "user",
        "user-tie",
        "user-group",
        "plus",
        "minus",
        "volleyball",
        "triangle-exclamation",
        "expand",
        "x",
        "location-dot",
        "arrow-down-wide-short",
        "magnifying-glass-plus",
        "paper-plane",
        "up-right-from-square",
        "shirt",
      ],
      regular: ["user", "circle-user", "clock", "comments", "paper-plane", "note-sticky"],
      brands: ["google"],
    },
  },
  components: false,
  app: {
    head: {
      title: "MVPApp",
      link: [{ rel: "icon", type: "image/png", href: "/favicon.png" }],
    },
  },
  runtimeConfig: {
    public: {
      apiRoute: process.env.API_ROUTE,
      backendURL: process.env.BACKEND_URL,
    },
  },
});
