import type Tournament from "~/interfaces/tournament/tournament";
import type Pools from "~/interfaces/pools/pools";
import type Rounds from "~/interfaces/rounds/rounds";
import type Team from "~/interfaces/teams/team";
import type Venues from "~/interfaces/venues/venues";
import type Clubs from "~/interfaces/clubs/club";
import type Courts from "~/interfaces/courts/courts";
import type Conflict from "~/interfaces/conflicts/conflict";
import type Suggestion from "~/interfaces/suggestions/suggestion";
import type Message from "~/interfaces/messages/message";
import type Penalty from "~/interfaces/games/penalty";
import type {GamePlan} from "~/interfaces/gamePlan/gamePlan";
import type {Note} from "~/interfaces/games/notes";

export default interface Game {
    id: number;
    number: number;
    date?: Date | null | string;
    time?: string | null;
    status_id?: number | null;
    points_home?: number | null;
    points_away?: number | null;
    venue_id?: number | null;
    court_id?: number | null;
    team_id_winner?: number | null;
    team_id_home?: number | null;
    team_id_away?: number | null;
    tournament_id?: number | null;
    pool_id?: number | null;
    group_id?: number | null;
    round_id?: number | null;
    is_deleted?: boolean | null;
    last_official_date?: Date | null;
    last_official_time?: string | null;
    last_official_court_id?: number | null;
    season_sport_id?: number | null;
    original_term_date?: Date | null;
    is_locked?: boolean | null;
    force_next_update?: boolean | null;
    original_home_team_id?: number | null;
    organizer_club_id?: number | null;
    organizer_team_id?: number | null;
    pin_code?: number | null;
    stats_calculated?: number | null;
    star_rating?: number | null;
    title_prefix?: string | null;
    sync_method?: number | null;
    home_penalty1?: number | null;
    home_penalty2?: number | null;
    home_penalty3?: number | null;
    home_penalty4?: number | null;
    away_penalty1?: number | null;
    away_penalty2?: number | null;
    away_penalty3?: number | null;
    away_penalty4?: number | null;
    penalty_status_id?: number | null;
    home_key?: number | null;
    away_key?: number | null;
    draft_id?: number | null;
    auto_time?: boolean | null;
    pool_points_fixed_home?: number | null;
    pool_points_fixed_away?: number | null;
    pool_bonus_fixed_home?: number | null;
    pool_bonus_fixed_away?: number | null;
    tournament?: Tournament;
    pool?: Pools;
    Round?: Rounds;
    home_team: Team;
    guest_team: Team;
    venue?: Venues;
    club?: Clubs;
    court?: Courts;
    conflict?: Conflict;
    suggestion?: Suggestion;
    messages?: Message[];
    penalties?: Penalty[];
    gamePlans: GamePlan[];
    notes?: Note[];
}