import type Tournament from "~/interfaces/tournament/tournament";
import type Pools from "~/interfaces/pools/pools";
import type Rounds from "~/interfaces/rounds/rounds";
import type Team from "~/interfaces/teams/team";
import type Venues from "~/interfaces/venues/venues";
import type Clubs from "~/interfaces/clubs/club";
import type Courts from "~/interfaces/courts/courts";
import type Conflict from "~/interfaces/conflicts/conflict";
import type Suggestion from "~/interfaces/suggestions/suggestion";
import type Message from "~/interfaces/messages/message";
import type Penalty from "~/interfaces/games/penalty";
import type {GamePlan} from "~/interfaces/gamePlan/gamePlan";
import type {Note} from "~/interfaces/games/notes";

export default interface Game {
    id: number;
    number: number;
    date?: Date | null | string;
    time?: string | null;
    statusId?: number | null;
    pointsHome?: number | null;
    pointsAway?: number | null;
    venueId?: number | null;
    courtId?: number | null;
    teamIdWinner?: number | null;
    teamIdHome?: number | null;
    teamIdAway?: number | null;
    tournamentId?: number | null;
    poolId?: number | null;
    groupId?: number | null;
    roundId?: number | null;
    isDeleted?: boolean | null;
    lastOfficialDate?: Date | null;
    lastOfficialTime?: string | null;
    lastOfficialCourtId?: number | null;
    seasonSportId?: number | null;
    originalTermDate?: Date | null;
    isLocked?: boolean | null;
    forceNextUpdate?: boolean | null;
    originalHomeTeamId?: number | null;
    organizerClubId?: number | null;
    organizerTeamId?: number | null;
    pinCode?: number | null;
    statsCalculated?: number | null;
    starRating?: number | null;
    titlePrefix?: string | null;
    syncMethod?: number | null;
    homePenalty1?: number | null;
    homePenalty2?: number | null;
    homePenalty3?: number | null;
    homePenalty4?: number | null;
    awayPenalty1?: number | null;
    awayPenalty2?: number | null;
    awayPenalty3?: number | null;
    awayPenalty4?: number | null;
    penaltyStatusId?: number | null;
    homeKey?: number | null;
    awayKey?: number | null;
    draftId?: number | null;
    autoTime?: boolean | null;
    poolPointsFixedHome?: number | null;
    poolPointsFixedAway?: number | null;
    poolBonusFixedHome?: number | null;
    poolBonusFixedAway?: number | null;
    tournament?: Tournament;
    pool?: Pools;
    Round?: Rounds;
    homeTeam: Team;
    guestTeam: Team;
    venue?: Venues;
    club?: Clubs;
    court?: Courts;
    conflict?: Conflict;
    suggestion?: Suggestion;
    messages?: Message[];
    penalties?: Penalty[];
    gamePlans: GamePlan[];
    notes?: Note[];
}